version: "3.7"
services:
  app:
    container_name: cleezy-app
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - --database-file-path=/tmp/urldatabase.db
      - --qr-code-cache-path=/tmp/
      - --qr-code-cache-state-file=/tmp/cleezy-state
      - --qr-code-base-url=https://sce.sjsu.edu/s
      - --qr-code-center-image-path=/app/assets/SCE_logo.png
      - --paste-directory=/app/pastes
      - -vvv
    volumes:
      - cleezy_data:/tmp/
      - ./server.py:/app/server.py
      - ./modules:/app/modules
      - ./assets:/app/assets
      - ./pastes:/app/pastes
    env_file:
      - .env

volumes:
  cleezy_data:

networks:
  default:
    external:
      name: sce
