version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command:
       - --database-file-path=/tmp/urldatabase.db
       - -vvv
    ports:
      - '8000:8000'
    volumes:
      - cleezy_data:/tmp/
  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  cleezy_data:
