version: '3.7'
services:
  app:
    container_name: cleezy-app
    build:
      context: .
      dockerfile: Dockerfile
    command:
       - --database-file-path=/tmp/urldatabase.db
       - -vvv
    volumes:
      - cleezy_data:/tmp/
    ports:
      - 8000:8000
  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
  nginx:
    container_name: cleezy-nginx
    image: nginx:alpine
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  cleezy_data:

networks: 
  default:
    external: 
      name: sce
