version: "3.7"
services:
  app:
    container_name: cleezy-app-dev
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - --database-file-path=/tmp/urldatabase.db
      - --port=8000
      - -vvv
    ports:
      - 8000:8000
    volumes:
      - cleezy_data_dev:/tmp/
      - ./server.py:/app/server.py
      - ./modules:/app/modules
    environment:
      - WATCHFILES_FORCE_POLLING=true
  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090

volumes:
  cleezy_data_dev:
