version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command:
       - --database-file-path=/tmp/urldatabase.db
       - -vvv
    ports:
      - '8000:8000'
    volumes:
      - cleezy_data:/tmp/

volumes:
  cleezy_data:
